package util;

import javax.swing.DefaultComboBoxModel;

public class ComboBoxModel{

	public static DefaultComboBoxModel<String> paisesModel(){
		DefaultComboBoxModel<String> model = new DefaultComboBoxModel<String>();
		model.addElement("Afganistán");
		model.addElement("Albania");
		model.addElement("Alemania");
		model.addElement("Andorra");
		model.addElement("Angola");
		model.addElement("Antigua y Barbuda");
		model.addElement("Arabia Saudita");
		model.addElement("Argelia");
		model.addElement("Argentina");
		model.addElement("Armenia");
		model.addElement("Australia");
		model.addElement("Austria");
		model.addElement("Azerbaiyán");
		model.addElement("Bahamas");
		model.addElement("Bangladés");
		model.addElement("Barbados");
		model.addElement("Baréin");
		model.addElement("Bélgica");
		model.addElement("Belice");
		model.addElement("Benín");
		model.addElement("Bielorrusia");
		model.addElement("Birmania");
		model.addElement("Bolivia");
		model.addElement("Bosnia y Herzegovina");
		model.addElement("Botsuana");
		model.addElement("Brasil");
		model.addElement("Brunéi");
		model.addElement("Bulgaria");
		model.addElement("Burkina Faso");
		model.addElement("Burundi");
		model.addElement("Bután");
		model.addElement("Cabo Verde");
		model.addElement("Camboya");
		model.addElement("Camerún");
		model.addElement("Canadá");
		model.addElement("Catar");
		model.addElement("Chad");
		model.addElement("Chile");
		model.addElement("China");
		model.addElement("Chipre");
		model.addElement("Ciudad del Vaticano");
		model.addElement("Colombia");
		model.addElement("Comoras");
		model.addElement("Corea del Norte");
		model.addElement("Corea del Sur");
		model.addElement("Costa de Marfil");
		model.addElement("Costa Rica");
		model.addElement("Croacia");
		model.addElement("Cuba");
		model.addElement("Dinamarca");
		model.addElement("Dominica");
		model.addElement("Ecuador");
		model.addElement("Egipto");
		model.addElement("El Salvador");
		model.addElement("Emiratos Árabes Unidos");
		model.addElement("Eritrea");
		model.addElement("Eslovaquia");
		model.addElement("Eslovenia");
		model.addElement("España");
		model.addElement("Estados Unidos de América");
		model.addElement("Estonia");
		model.addElement("Eswatini");
		model.addElement("Etiopía");
		model.addElement("Filipinas");
		model.addElement("Finlandia");
		model.addElement("Fiyi");
		model.addElement("Francia");
		model.addElement("Gabón");
		model.addElement("Gambia");
		model.addElement("Georgia");
		model.addElement("Ghana");
		model.addElement("Granada");
		model.addElement("Grecia");
		model.addElement("Guatemala");
		model.addElement("Guinea");
		model.addElement("Guinea-Bisáu");
		model.addElement("Guinea Ecuatorial");
		model.addElement("Guyana");
		model.addElement("Haití");
		model.addElement("Honduras");
		model.addElement("Hungría");
		model.addElement("India");
		model.addElement("Indonesia");
		model.addElement("Irak");
		model.addElement("Irán");
		model.addElement("Irlanda");
		model.addElement("Islandia");
		model.addElement("Islas Marshall");
		model.addElement("Islas Salomón");
		model.addElement("Israel");
		model.addElement("Italia");
		model.addElement("Jamaica");
		model.addElement("Japón");
		model.addElement("Jordania");
		model.addElement("Kazajistán");
		model.addElement("Kenia");
		model.addElement("Kirguistán");
		model.addElement("Kiribati");
		model.addElement("Kuwait");
		model.addElement("Laos");
		model.addElement("Lesoto");
		model.addElement("Letonia");
		model.addElement("Líbano");
		model.addElement("Liberia");
		model.addElement("Libia");
		model.addElement("Liechtenstein");
		model.addElement("Lituania");
		model.addElement("Luxemburgo");
		model.addElement("Macedonia del Norte");
		model.addElement("Madagascar");
		model.addElement("Malasia");
		model.addElement("Malaui");
		model.addElement("Maldivas");
		model.addElement("Malí");
		model.addElement("Malta");
		model.addElement("Marruecos");
		model.addElement("Mauricio");
		model.addElement("Mauritania");
		model.addElement("México");
		model.addElement("Micronesia");
		model.addElement("Moldavia");
		model.addElement("Mónaco");
		model.addElement("Mongolia");
		model.addElement("Montenegro");
		model.addElement("Mozambique");
		model.addElement("Namibia");
		model.addElement("Nauru");
		model.addElement("Nepal");
		model.addElement("Nicaragua");
		model.addElement("Níger");
		model.addElement("Nigeria");
		model.addElement("Noruega");
		model.addElement("Nueva Zelanda");
		model.addElement("Omán");
		model.addElement("Países Bajos");
		model.addElement("Pakistán");
		model.addElement("Palaos");
		model.addElement("Panamá");
		model.addElement("Papúa Nueva Guinea");
		model.addElement("Paraguay");
		model.addElement("Perú");
		model.addElement("Polonia");
		model.addElement("Portugal");
		model.addElement("Reino Unido");
		model.addElement("República Centroafricana");
		model.addElement("República Checa");
		model.addElement("República del Congo");
		model.addElement("República Democrática del Congo");
		model.addElement("República Dominicana");
		model.addElement("República Sudafricana");
		model.addElement("Ruanda");
		model.addElement("Rumania");
		model.addElement("Rusia");
		model.addElement("Samoa");
		model.addElement("San Cristóbal y Nieves");
		model.addElement("San Marino");
		model.addElement("San Vicente y las Granadinas");
		model.addElement("Santa Lucía");
		model.addElement("Santo Tomé y Príncipe");
		model.addElement("Senegal");
		model.addElement("Serbia");
		model.addElement("Seychelles");
		model.addElement("Sierra Leona");
		model.addElement("Singapur");
		model.addElement("Siria");
		model.addElement("Somalia");
		model.addElement("Sri Lanka");
		model.addElement("Suazilandia o Eswatini");
		model.addElement("Sudán");
		model.addElement("Sudán del Sur");
		model.addElement("Suecia");
		model.addElement("Suiza");
		model.addElement("Surinam");
		model.addElement("Tailandia");
		model.addElement("Tanzania");
		model.addElement("Tayikistán");
		model.addElement("Timor Oriental");
		model.addElement("Togo");
		model.addElement("Tonga");
		model.addElement("Trinidad y Tobago");
		model.addElement("Túnez");
		model.addElement("Turkmenistán");
		model.addElement("Turquía");
		model.addElement("Tuvalu");
		model.addElement("Ucrania");
		model.addElement("Uganda");
		model.addElement("Uruguay");
		model.addElement("Uzbekistán");
		model.addElement("Vanuatu");
		model.addElement("Venezuela");
		model.addElement("Vietnam");
		model.addElement("Yemen");
		model.addElement("Yibuti");
		model.addElement("Zambia");
		model.addElement("Zimbabue");

		return model;
	}
	
	public static DefaultComboBoxModel<String> profesionesModel(){
		DefaultComboBoxModel<String> model = new DefaultComboBoxModel<String>();
		model.addElement("Abogado/a");
		model.addElement("Arquitecto/a");
		model.addElement("Deportista");
		model.addElement("Diseñador/a");
		model.addElement("Economista");
		model.addElement("Editor/a");
		model.addElement("Electricista");
		model.addElement("Filósofo/a");
		model.addElement("Físico/a");
		model.addElement("Historiador/a");
		model.addElement("Informático/a");
		model.addElement("Ingeniero/a Automático/a");
		model.addElement("Ingeniero/a Civil");
		model.addElement("Ingeniero/a Eléctrico/a");
		model.addElement("Ingeniero/a Geofísico/a");
		model.addElement("Ingeniero/a Hidráulico/a");
		model.addElement("Ingeniero/a Industrial");
		model.addElement("Ingeniero/a Informático/a");
		model.addElement("Ingeniero/a Químico/a");
		model.addElement("Ingeniero/a Mecánico/a");
		model.addElement("Ingeniero/a en Telecomunicaciones");
		model.addElement("Juez/a");
		model.addElement("Matemático/a");
		model.addElement("Médico");
		model.addElement("Militar");
		model.addElement("Músico");
		model.addElement("Político/a");
		return model;
	}

}
